In [103]:
import seaborn as sns
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib

pd_data = pd.read_csv('이륜차신고현황_시도별_20230309164825.csv', encoding = 'cp949')
pd_data.drop(0, axis = 0, inplace = True)
pd_data.columns = ['시도명', '시점', '시군구', '경형합계', '소형합계', '중형합계', '대형합계', '관용경형', '관용소형', '관용중형', '관용대형', '자가용경형', '자가용소형', '자가용중형', '자가용대형']
pd_data

,시도명,시점,시군구,경형합계,소형합계,중형합계,대형합계,관용경형,관용소형,관용중형,관용대형,자가용경형,자가용소형,자가용중형,자가용대형
1,부산,2023.01,금정구,350,2072,5178,575,5,4,68,2,345,2068,5110,573
2,부산,2023.01,기장군,311,1473,3475,627,2,8,58,0,309,1465,3417,627
3,부산,2023.01,남구,451,2408,6964,941,3,10,18,0,448,2398,6946,941
4,부산,2023.01,동구,185,963,3009,321,2,22,32,1,183,941,2977,320
5,부산,2023.01,동래구,404,2133,5584,855,1,1,71,1,403,2132,5513,854
6,부산,2023.01,부산진구,633,3922,10094,1397,10,21,86,1,623,3901,10008,1396
7,부산,2023.01,북구,414,2075,5532,720,1,4,45,0,413,2071,5487,720
8,부산,2023.01,사상구,576,2276,5989,603,26,38,96,1,550,2238,5893,602
9,부산,2023.01,사하구,528,2888,8168,969,6,2,72,0,522,2886,8096,969
10,부산,2023.01,서구,207,1486,4033,342,1,6,2,0,206,1480,4031,342
11,부산,2023.01,수영구,307,1472,4297,675,0,4,80,1,307,1468,4217,674
12,부산,2023.01,연제구,279,1591,4451,681,5,4,89,36,274,1587,4362,645
13,부산,2023.01,영도구,221,1482,4374,344,5,2,43,0,216,1480,4331,344
14,부산,2023.01,해운대구,544,2926,7988,1333,7,2,86,1,537,2924,7902,1332
15,부산,2023.01,부산기타,0,10,2,0,0,0,0,0,0,10,2,0

In [164]:
fil_list = ['관용경형', '관용소형', '관용중형', '관용대형', '자가용경형', '자가용소형','자가용중형', '자가용대형']
for i in fil_list:
    pd_data[i] = pd_data[i].astype(np.int64)
for e in pd_data[fil_list]:
    print(e, pd_data[e].sum())
    
# print(sum(pd_data[fil_list]))
# _, axe = plt.subplots()
# axe.pie(pd_data[fil_list])
pd_data.sum()

관용경형 74
관용소형 128
관용중형 846
관용대형 44
자가용경형 5336
자가용소형 29049
자가용중형 78292
자가용대형 10339

시도명                         부산부산부산부산부산부산부산부산부산부산부산부산부산부산부산
시점       2023.012023.012023.012023.012023.012023.012023...
시군구           금정구기장군남구동구동래구부산진구북구사상구사하구서구수영구연제구영도구해운대구부산기타
경형합계           3503114511854046334145765282073072792215440
소형합계     2072147324089632133392220752276288814861472159...
중형합계     5178347569643009558410094553259898168403342974...
대형합계         575627941321855139772060396934267568134413330
관용경형                                                    74
관용소형                                                   128
관용중형                                                   846
관용대형                                                    44
자가용경형                                                 5336
자가용소형                                                29049
자가용중형                                                78292
자가용대형                                                10339
dtype: object